volumes:
  data-volume:


services:
  wp-app:
    build: .
    container_name: wp-app
    ports:
      - 3333:80
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins:rw

  wp-db:
    image: mariadb:10.4
    restart: unless-stopped
    container_name: wp-database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - data-volume:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: wp-db
        PMA_USER: ${DB_USER}
        PMA_PASSWORD: ${DB_PASSWORD}
      ports:
        - "8000:80"
      depends_on:
        - wp-db